FROM node:14 as build

RUN mkdir /app

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock

RUN yarn install

COPY . .

RUN yarn test -- --watchAll=false --u

RUN yarn build

FROM nginx

COPY --from=build /app/build /usr/share/nginx/html

ADD default.conf /etc/nginx/conf.d/