version: '3'

services:
    main:
      build:
        context: .
      ports:
        - 3003:3000
      volumes:
        - .:/app
      restart: always
      environment: 
        - DB=syrf_db
        - DB_USER=syrf
        - DB_PASSWORD=SJ2cc2ON72sXX
        - DB_HOST=db
      restart: always
    db:
      image: mariadb:10.6
      volumes:
        - ./volumes/db_volume:/var/lib/mysql
      ports:
        - ${DB_PORT}:3306
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=syrf
        - MYSQL_PASSWORD=SJ2cc2ON72sXX
        - MYSQL_DATABASE=syrf_db
      ports:
        - 3072:3306
      restart: always
    
    