name: SYRF My Sailing Profile 

on: [push] # tells github to run this on any push to the repository

jobs:
 build-and-push-image-develop:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.ref == 'refs/heads/SNS-224'
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}{% raw %}

        - name: Build and push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: Dockerfile-staging
            push: true
            tags: {% raw %}${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

  test: # names the job
    runs-on: ubuntu-latest # sets the version of linux we want to use, should be what you have on your server

    strategy:
      fail-fast: false # tells github to not run further steps if this one fails
      matrix:
        node-version: [12.x] # sets the version of node we want to use, should be what you have on your server

    if: github.ref == 'refs/heads/SNS-224'
      steps:
        - uses: actions/checkout@v2 # fetches your commit to test it
        - name: Use Node.js ${{ matrix.node-version }} # names our step
          uses: actions/setup-node@v1 # downloads node and npm
          with:
            node-version: ${{ matrix.node-version }}
        - run: yarn install # installs your dependencies
        - run: yarn test # runs your test suite
          env:
            CI: true # shows terminal output!
          
#   deploy:
#     runs-on: ubuntu-latest
#     needs: test # this job depends on "test" having finished
#     if: github.ref == 'refs/heads/develop' # we tell Github to only execute this step if we're on our develop branch (so we don't put unfinished branches in production)
#     steps:
#       - name: Deploy SYRF My Sailing Profile app in Staging environment.
#         uses: appleboy/ssh-action@master # An action made to control Linux servers
#         env:
#           SSH_PRIVATE_KEY: ${{secrets.SSH_KEY_PEM}}
# #         with: # We set all our secrets here for the action, these won't be shown in the action logs
# #           script: |